.TH XMINICOM 1 "September 14, 1998" "" "Linux Users Manual"
.SH NAME
xminicom \- friendly serial communication program
.SH SYNOPSIS
.B xminicom
.I minicom-options
.SH DESCRIPTION
.B Xminicom
is a script wrapper around
.I minicom.
It tries to find a color capable xterm or rxvt on your system, and
then runs minicom with the \-c (color) flag in a terminal session.
.SH OPTIONS
See
.I minicom
(1).
.SH AUTHOR
Miquel van Smoorenburg, miquels@cistron.nl
.SH "SEE ALSO"
minicom(1)
